### ISSUE TITLE
やりたいこと

### ISSUE THREAD

**Issue by vestige** [mame-n/toteka04_timer#4]
タイマー中に ”topeka 04”  をだしておきたい
人の右手に"8888"、左手に"Last 10"を表示しておく

残り１０秒になったら、playerを左に向けて、Last 10を表示する
１０秒タイマー開始

残り０秒になったら、playerを右に向ける
８８８８をみせる

**Comment by mame-n** [comment]
> タイマー中に ”topeka 04” をだしておきたい
これって、どんなイメージ?

**Comment by mame-n** [comment]
> タイマー中に ”topeka 04” をだしておきたい

これってどんなイメージ?

[timerdesign.pdf](https://github.com/mame-n/toteka04_timer/files/160745/timerdesign.pdf)

**Comment by vestige** [comment]
あーw
これはなかなかいい感じかもですね。

**Comment by mame-n** [comment]
ユーザーコマンドは
- timer start
- pause/resume
- reset  : 0にする
- set time

だったかな。

**Comment by vestige** [comment]
確認したー
